## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.30735645 0.96800161 0.88962378 0.95090233 0.4439431 ]
 [0.33222596 0.38018452 0.99589239 0.64273893 0.57506016]
 [0.45842038 0.34163684 0.81398717 0.94009364 0.74694264]]


#### 연산 함수
 - add, subtract, multiply, divide

In [3]:
np.add(x,y) # ndarray 두 개의 shape이 같아야함

array([[ 0.30735645,  1.96800161,  2.88962378,  3.95090233,  4.4439431 ],
       [ 5.33222596,  6.38018452,  7.99589239,  8.64273893,  9.57506016],
       [10.45842038, 11.34163684, 12.81398717, 13.94009364, 14.74694264]])

In [5]:
np.subtract(x,y)

array([[-0.30735645,  0.03199839,  1.11037622,  2.04909767,  3.5560569 ],
       [ 4.66777404,  5.61981548,  6.00410761,  7.35726107,  8.42493984],
       [ 9.54157962, 10.65836316, 11.18601283, 12.05990636, 13.25305736]])

In [6]:
np.multiply(x,y)

array([[ 0.        ,  0.96800161,  1.77924756,  2.85270699,  1.77577239],
       [ 1.66112982,  2.28110715,  6.97124676,  5.14191144,  5.17554141],
       [ 4.5842038 ,  3.75800529,  9.767846  , 12.22121738, 10.45719703]])

In [7]:
np.divide(x,y)

array([[ 0.        ,  1.03305613,  2.24814134,  3.15489814,  9.01016374],
       [15.04999772, 15.78181019,  7.02887183, 12.44673323, 15.65053656],
       [21.8140389 , 32.19793233, 14.74224717, 13.82840962, 18.74307231]])

In [8]:
x+y

array([[ 0.30735645,  1.96800161,  2.88962378,  3.95090233,  4.4439431 ],
       [ 5.33222596,  6.38018452,  7.99589239,  8.64273893,  9.57506016],
       [10.45842038, 11.34163684, 12.81398717, 13.94009364, 14.74694264]])

In [9]:
x-y

array([[-0.30735645,  0.03199839,  1.11037622,  2.04909767,  3.5560569 ],
       [ 4.66777404,  5.61981548,  6.00410761,  7.35726107,  8.42493984],
       [ 9.54157962, 10.65836316, 11.18601283, 12.05990636, 13.25305736]])

In [10]:
x/y

array([[ 0.        ,  1.03305613,  2.24814134,  3.15489814,  9.01016374],
       [15.04999772, 15.78181019,  7.02887183, 12.44673323, 15.65053656],
       [21.8140389 , 32.19793233, 14.74224717, 13.82840962, 18.74307231]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [11]:
print(y)

[[0.30735645 0.96800161 0.88962378 0.95090233 0.4439431 ]
 [0.33222596 0.38018452 0.99589239 0.64273893 0.57506016]
 [0.45842038 0.34163684 0.81398717 0.94009364 0.74694264]]


In [12]:
y.mean() #평균

0.6524673279923108

In [13]:
np.mean(y)

0.6524673279923108

In [14]:
np.max(y)

0.9958923942684219

In [15]:
np.argmax(y) #가장 큰 값의 인덱스

7

In [16]:
np.var(y) #분산

0.06401233921988755

In [17]:
np.median(y) #중앙값

0.6427389301806021

In [18]:
np.std(y) #표준편차

0.2530065991627245

In [31]:
np.std(np.arange(1, 5))

1.118033988749895

In [20]:
x = [1,2,3,4,5]

np.mean(x)

3.0

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [21]:
y

array([[0.30735645, 0.96800161, 0.88962378, 0.95090233, 0.4439431 ],
       [0.33222596, 0.38018452, 0.99589239, 0.64273893, 0.57506016],
       [0.45842038, 0.34163684, 0.81398717, 0.94009364, 0.74694264]])

In [22]:
np.sum(y)

9.787009919884662

In [24]:
np.sum(y, axis=0) #축을 따라서 합을 구함 

array([1.09800279, 1.68982298, 2.69950334, 2.53373491, 1.7659459 ])

In [25]:
np.sum(y, axis=1) #축을 따라서 합을 구함 

array([3.55982727, 2.92610197, 3.30108068])

In [23]:
np.cumsum(y) #뒤의 원소는 앞의 수와 본인의 합을 나타냄 (누적되는 것)

array([0.30735645, 1.27535806, 2.16498184, 3.11588417, 3.55982727,
       3.89205323, 4.27223776, 5.26813015, 5.91086908, 6.48592924,
       6.94434962, 7.28598646, 8.09997363, 9.04006728, 9.78700992])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [26]:
z = np.random.randn(10)
z

array([ 1.14649853, -0.11479237,  1.09011304, -0.38083362, -2.28370202,
        0.50273954,  1.48902944,  1.0300818 , -0.23777925, -0.19657966])

In [28]:
z > 0

array([ True, False,  True, False, False,  True,  True,  True, False,
       False])

In [27]:
np.any(z>0) #하나라도 참이면 True 반환

True

In [29]:
np.all(z>0) #모두 참이면 True 반환

False

In [30]:
np.all(z != 0) #모두 참이면 True 반환

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [32]:
z = np.random.randn(10)
z

array([ 1.0823223 , -2.01041219, -0.37262123,  1.72054965, -1.3653754 ,
        2.69542699, -1.29464213, -1.37309313, -0.7302836 , -2.00291337])

In [33]:
np.where(z>0, z, 0) #z>0이면 z를 쓰고 아닌 경우 0으로 반환 / 음수는 0으로 변환

array([1.0823223 , 0.        , 0.        , 1.72054965, 0.        ,
       2.69542699, 0.        , 0.        , 0.        , 0.        ])