## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.83162889 0.85226409 0.27514717 0.36839103 0.7859869 ]
 [0.71683902 0.72983839 0.07280771 0.61998125 0.27279969]
 [0.07984163 0.06898872 0.19776785 0.93000651 0.20165262]]


In [3]:
x + y

array([[ 0.83162889,  1.85226409,  2.27514717,  3.36839103,  4.7859869 ],
       [ 5.71683902,  6.72983839,  7.07280771,  8.61998125,  9.27279969],
       [10.07984163, 11.06898872, 12.19776785, 13.93000651, 14.20165262]])

* Scalar(상수)와의 연산

In [4]:
x + 2 #모든 원소에 2를 더함

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [4]:
x * 2 #모든 원소에 2를 곱함

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x / 2 #모든 원소에 2를 나눔

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])

In [6]:
x ** 2 #모든 원소에 2를 제곱

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [8]:
x % 2 == 0 #모든 원소 짝수 / 불린 형태

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [19]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000,1004)
d = b.reshape(1,3)
print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [20]:
print(a.shape) #뒤부터 비교함 3,3연산은 가능하나 3,4연산은 안됨
print(b.shape)
print(c.shape)
print(d.shape) #뒤가 3이므로 a와 연산 가능

(4, 3)
(3,)
(4,)
(1, 3)


In [11]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [21]:
# a + c error

In [22]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])