### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2,3)

array([[0.51805919, 0.70538037, 0.28490845],
       [0.75431839, 0.44748451, 0.95278344]])

In [5]:
np.random.rand(5)

array([0.85711446, 0.3819803 , 0.06646758, 0.97528345, 0.80203283])

In [3]:
np.random.rand(4,5,3)

array([[[0.89452058, 0.79379101, 0.33550644],
        [0.98053802, 0.89820876, 0.4581132 ],
        [0.4663728 , 0.05567153, 0.22102645],
        [0.25548326, 0.96146413, 0.75813874],
        [0.85029573, 0.3154489 , 0.24982338]],

       [[0.91838777, 0.58448994, 0.12667555],
        [0.50765212, 0.73855907, 0.72706784],
        [0.88738865, 0.05387605, 0.52725074],
        [0.70202432, 0.70019042, 0.27181037],
        [0.9094896 , 0.96529875, 0.26236792]],

       [[0.3497954 , 0.32297954, 0.72520867],
        [0.00742706, 0.13447154, 0.58484094],
        [0.65847962, 0.32692883, 0.21465778],
        [0.32923774, 0.78760794, 0.46776307],
        [0.09784407, 0.08499759, 0.94214765]],

       [[0.28124828, 0.59599097, 0.83290459],
        [0.9738956 , 0.29703348, 0.60993465],
        [0.68537794, 0.89332517, 0.74940548],
        [0.17606084, 0.69657031, 0.03571581],
        [0.66605984, 0.69052426, 0.87655148]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [6]:
np.random.randn(5)

array([-0.45179916,  0.08628136,  1.32102775, -1.00741835, -0.25740139])

In [7]:
np.random.randn(3,4)

array([[-0.32229552,  0.58942897, -1.12485287, -0.32747321],
       [ 1.1386342 , -1.11526846, -0.17084629, -1.75900464],
       [ 1.88623319,  0.23144937,  1.09802342, -1.89058252]])

In [8]:
np.random.randn(3,4,2)

array([[[ 0.26960182,  0.35084458],
        [ 0.65117245, -0.88359818],
        [ 0.52606421,  0.15383101],
        [ 0.93328663, -0.71249155]],

       [[ 0.11304856, -1.48304862],
        [-0.45255511, -1.34699659],
        [-0.07584512, -0.88205032],
        [-0.37630221,  0.62640733]],

       [[-0.35645659,  0.82516855],
        [ 0.59104473,  0.37381785],
        [-0.42472253,  0.31207415],
        [-0.5857517 , -0.60269273]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [10]:
np.random.randint(1,100,size=(3,5))

array([[71, 68, 79, 74,  2],
       [94, 47, 14, 57, 67],
       [ 1, 91, 67, 25,  9]])

In [11]:
np.random.randint(1,100,5)

array([64,  3, 17, 30, 72])

In [12]:
np.random.randint(1,100,(2,3))

array([[80,  5, 13],
       [30, 81, 62]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [21]:
np.random.seed(100) #숫자는 아무거나 넣으면 됨
np.random.randn(3,4) #값이 고정됨

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [22]:
np.random.choice(100, (3, 4)) #0~99중 3,4로 가져오게

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [23]:
x= np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,(2,2))

array([[1.5, 1. ],
       [3. , 2. ]])

In [26]:
x= np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,(2,2), replace=False)

array([[2. , 4.9],
       [1.5, 1. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [30]:
np.random.uniform(1.0, 3.0, size=(4,5))

array([[2.78109189, 2.153803  , 2.48495938, 2.26036787, 2.16368438],
       [1.04087826, 1.42005316, 2.08936976, 2.53823034, 1.50139046],
       [1.57179138, 2.70479018, 2.95001299, 2.76970659, 1.71901569],
       [2.19771789, 1.70959122, 1.68038043, 1.35616198, 1.47538842]])

In [32]:
np.random.normal(size=(3,4))

array([[ 1.29974807, -1.73309562, -0.9833101 ,  0.35750775],
       [-1.6135785 ,  1.47071387, -1.1880176 , -0.54974619],
       [-0.94004616, -0.82793236,  0.10886347,  0.50780959]])

In [33]:
np.random.randn(3,4)

array([[-0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855],
       [-1.6355294 , -1.04420988,  0.61303888,  0.73620521]])