## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,100, size=10)
x

array([79, 48, 49, 54,  6, 96, 31, 49, 69, 45])

In [4]:
even_mask = x % 2 == 0
even_mask

array([False,  True, False,  True,  True,  True, False, False, False,
       False])

- bool 리스트를 인덱스로 전달

In [5]:
x[even_mask]

array([48, 54,  6, 96])

In [6]:
x[x % 2 ==0]

array([48, 54,  6, 96])

In [7]:
x[x > 30]

array([79, 48, 49, 54, 96, 31, 49, 69, 45])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [8]:
# 아래의 두조건 모두 만족 and(&)
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)]

array([6])

In [9]:
#30보다 작거나 50보다 큰 것
x[(x < 30) | (x < 50)]

array([48, 49,  6, 31, 49, 45])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [11]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
temp

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7,
       28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [12]:
len(temp[temp > 25])

21

In [16]:
np.sum(temp > 25)

21

In [14]:
np.mean(temp[temp > 25])

26.857142857142858