## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3,3)
x

array([[0.86354388, 0.57601157, 0.17290922],
       [0.47225736, 0.38074685, 0.83502122],
       [0.62641361, 0.86306768, 0.74591016]])

In [3]:
np.linalg.inv(x)

array([[ 1.75044353,  1.12408122, -1.66414077],
       [-0.68468971, -2.14783801,  2.5631498 ],
       [-0.67778685,  1.54119067, -0.22754927]])

In [4]:
x @ np.linalg.inv(x) #행렬의 곱은 @골뱅이로 표시
np.matmul(x, np.linalg.inv(x)) #또는 행렬의 곱 matmul 사용 

array([[ 1.00000000e+00,  1.64010434e-16, -2.45186552e-16],
       [ 1.06643047e-16,  1.00000000e+00,  4.26689108e-17],
       [ 8.07081239e-18, -3.18816139e-17,  1.00000000e+00]])

In [6]:
#x = np.random.rand(3,4) # linAlgError 행렬은 3,3 처럼 값이 정사각형 꼴이어야함
x = np.random.rand(3,3,3)
x @ np.linalg.inv(x) #행렬의 곱은 @골뱅이로 표시
np.matmul(x, np.linalg.inv(x)) #또는 행렬의 곱 matmul 사용 

array([[[ 1.00000000e+00, -9.83548687e-17, -2.65011203e-16],
        [-1.68852024e-16,  1.00000000e+00, -1.59658440e-16],
        [ 2.35618352e-17, -8.56834079e-17,  1.00000000e+00]],

       [[ 1.00000000e+00,  6.62299576e-17,  1.37134786e-16],
        [ 1.21733493e-16,  1.00000000e+00,  8.03005985e-17],
        [ 6.49422276e-17, -2.24517027e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -3.06740347e-17,  4.05152131e-17],
        [ 5.04569501e-17,  1.00000000e+00, -3.93490127e-16],
        [ 6.59785437e-18, -1.38064170e-16,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [7]:
A = np.array([[1,1],[2,4]])
B = np.array([25,64])

x = np.linalg.solve(A,B)
x

array([18.,  7.])

In [8]:
np.allclose(A@x, B)

True