## Numpy 연습문제1

#### 1. np이름으로 numpy 패키지 가져오기

In [2]:
import numpy as np

#### 2. numpy 버전 출력하기

In [3]:
np.__version__

'1.26.4'

#### 3. 모두 0의 값을 갖는 사이즈가 10인 벡터 생성하기

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 값 10~49를 갖는 벡터 생성하기

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. 0~8 사이의 정수 값을 3X3 크기로 갖는 행렬 생성하기 

In [11]:
np.random.randint(9, size=(3,3))

array([[5, 0, 6],
       [2, 8, 3],
       [7, 2, 5]])

#### 6. 실수 난수를 3X3X3의 크기로 갖는 배열 생성하기

In [12]:
np.random.rand(3,3,3)

array([[[0.16793606, 0.48157137, 0.34432324],
        [0.2442388 , 0.59126158, 0.28345845],
        [0.21927595, 0.18871027, 0.5467188 ]],

       [[0.25479537, 0.54003484, 0.12587062],
        [0.01542898, 0.10296242, 0.4389225 ],
        [0.21992565, 0.50960288, 0.48145217]],

       [[0.79300253, 0.05818749, 0.83632692],
        [0.2576087 , 0.41143737, 0.79239383],
        [0.28573524, 0.08882898, 0.02914716]]])